- id: check-readme
  name: Check for readme file
  description: Validate for readme file presense
  entry: check-readme.sh
  language: script

- id: validate-author-email
  name: Validate the author flux7 email address
  description: Valid flux7 email address
  entry: validate-author-email.sh
  language: script
