repos:
-   repo: https://github.com/Flux7Labs/central-repo-git-hooks.git
    rev: feat/US3323
    hooks:
    -   id: check-readme
    -   id: terraform-fmt
    -   id: packer-validate
    -   id: cfn-lint
    -   id: flake8-lint
