repos:
-   repo: https://github.com/Flux7Labs/central-repo-git-hooks.git
    rev: 'feat/US3719'
    hooks:
    -   id: check-readme
    -   id: validate-author-email
    -   id: terraform-fmt
    -   id: packer-validate
    -   id: cfn-lint
    -   id: flake8-lint

