- id: check-readme
  name: Check for readme file
  description: Validate for readme file presense
  entry: hooks/scripts/check-readme.sh
  language: script

- id: validate-author-email
  name: Validate the author flux7 email address
  description: Valid flux7 email address
  entry: hooks/scripts/validate-author-email.sh
  language: script

- id: terraform-security-test
  name: terraform-security-test
  description: 'runs the security test on the terraform infra files'
  entry: hooks/scripts/terraform_security_test.sh
  language: script
  pass_filenames: true
  always_run: true
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true
  args: "."

- id: terraform-fmt
  name: Terraform fmt
  description: Runs `terraform fmt` on all Terraform files
  language: script
  entry: hooks/scripts/terraform_fmt.sh
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: packer-validate
  name: Packer validate
  description: Runs `packer validate` on all staged packer files
  language: script
  entry: hooks/scripts/packer_validate.sh
  files: \.json$

- id: cfn-lint
  name: Cloudformation Lint
  description: Runs cfn-lint on CloudFormation Templates
  language: script
  entry: hooks/scripts/cfn_lint.sh
  files: (\.yml|\.yaml)$

- id: flake8-lint
  name: flake8-lint
  description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
  entry: 'flake8 --ignore=E501'
  language: system
  files: \.py$

