repos:
-   repo: https://github.com/Flux7Labs/central-repo-git-hooks.git
    rev: master
    hooks:
    -   id: check-readme
    -   id: validate-author-email
        args: ["@nttdata.com"]
    -   id: terraform-fmt
    -   id: packer-validate
    -   id: cfn-lint
        files: ./.*\.(json|yml|yaml)$
    -   id: flake8-lint
    -   id: security-check
    -   id: check-prtemplate
