repos:
-   repo: https://github.com/Flux7Labs/central-repo-git-hooks.git
    rev: master
    hooks:
    -   id: check-readme
    -   id: validate-author-email
    -   id: terraform-fmt
    -   id: packer-validate
    -   id: cfn-lint
    -   id: flake8

