- id: check-readme
  name: Check for readme file
  description: Validate for readme file presense
  entry: hooks/scripts/check-readme.sh
  language: script

- id: validate-author-email
  name: Validate the author flux7 email address
  description: Valid flux7 email address
  entry: hooks/scripts/validate-author-email.sh
  language: script

- id: terraform-fmt
  name: Terraform fmt
  description: Runs `terraform fmt` on all Terraform files
  language: script
  entry: hooks/scripts/terraform_fmt.sh
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: packer-validate
  name: Packer validate
  description: Runs `packer validate` on all staged packer files
  language: script
  entry: hooks/scripts/packer_validate.sh
  files: \.json$

- id: cfn-lint
  name: Cloudformation Lint
  description: Runs cfn-lint on CloudFormation Templates
  language: script
  entry: hooks/scripts/cfn_lint.sh
  files: (\.yml|\.yaml)$

- id: flake8-lint
  name: flake8-lint
  description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
  entry: hooks/scripts/python_lint.sh
  language: script
  files: (\.py)$   

# The below hooks are only required or used by a PR build and not required to be used by developers
- id: prbuild-cfn-lint
  name: prbuild-cfn-lint
  description: Runs cfn-lint on CloudFormation Templates when a pr build is invoked
  language: script
  entry: hooks/scripts/cfn_lint.sh
  args: [ "prbuild" ]

- id: prbuild-flake8-lint
  name: prbuild-flake8-lint
  description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
  entry: flake8
  # args: [ "prbuild" ]  
  language: script
  files: \.py$ 

